EXTRA_CFLAGS				+= -D_SDIO_ -DNO_FIRMWARE_CLASS
ks79xx_sdio-y				+= sdio/ks7010_sdio.o \
						ks_wlan_net.o \
						ks_hostif.o \
						ks_wlan_net.o \
						michael_mic.o \
						ks_debug.o

obj-$(CONFIG_KS7010_SDIO)			+= ks79xx_sdio.o 

